name: iGFAPStrokeAssistant
options:
  bundleIdPrefix: com.igfap
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en

targets:
  iGFAPStrokeAssistant:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: iGFAPStrokeAssistant
        name: iGFAPStrokeAssistant
        type: group
        createIntermediateGroups: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.igfap.iGFAPStrokeAssistant
        PRODUCT_NAME: iGFAPStrokeAssistant
        INFOPLIST_FILE: iGFAPStrokeAssistant/Info.plist
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: YES
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: NO
    dependencies:
      - framework: SwiftUI.framework
        embed: false
      - framework: Foundation.framework
        embed: false
      - framework: Combine.framework
        embed: false
      - framework: MapKit.framework
        embed: false
      - framework: CoreLocation.framework
        embed: false
      - framework: PDFKit.framework
        embed: false

  iGFAPStrokeAssistantTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: iGFAPStrokeAssistantTests
        name: iGFAPStrokeAssistantTests
        type: group
        createIntermediateGroups: true
    dependencies:
      - target: iGFAPStrokeAssistant
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.igfap.iGFAPStrokeAssistantTests
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        CODE_SIGN_STYLE: Automatic

schemes:
  iGFAPStrokeAssistant:
    build:
      targets:
        iGFAPStrokeAssistant: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - iGFAPStrokeAssistantTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
